### ISSUE TITLE
[Question]: Does this module still work with icingaweb2-module-monitoring?

### ISSUE THREAD

**Issue by jensrudolf** [NETWAYS/icingaweb2-module-grafana#20]
### Good Day.

Recently, we replaced https://github.com/Mikesch-mp/icingaweb2-module-grafana with this module due to PHP deprecation messages appearing within the web ui since the latest Icingaweb2 release.

However, after switching to this fork, the graphs completely disappeared within the (old) monitoring view but are only visible within the IcingaDB Web views. Seems like the grapher hooks are not working.

So my question is: does this fork still support the Icingaweb2 Monitoring Module?

If yes, is there a special configuration required to make the graphs appear?
If no, is there a chance to restore compatibility to not force users to switch to IcingaDB Web?

Many thanks anyway for your effort to maintain this module as for us, this is a critical part of our Icinga infrastructure. We really appriciate this.

**Comment by martialblog** [comment]
Hi, 

thanks for the feedback. The Fork is still a work in progress and we are planning a release by the end of the year.

We haven't touched much of the code yet so all functions of the latest upstream version [v2.0.3](https://github.com/Mikesch-mp/icingaweb2-module-grafana/releases/tag/v2.0.3) should be working.

Please note that the v2.0.0 release notes state:

> BREAKING CHANGES:
> Only [icingadb](https://github.com/Icinga/icingadb) backend for [icingadb-web](https://github.com/Icinga/icingadb-web) will be supported from now on.

https://github.com/Mikesch-mp/icingaweb2-module-grafana/releases/tag/v2.0.0

Regards,
Markus

**Comment by jensrudolf** [comment]
Hi @martialblog,

thank you so much for your quick response. I see that (legacy) Icingaweb2 Monitoring Module compatibility has already been removed upstream. Seems we were on an older release. That unfortunate.

However, are there any plans to restore compatibility with Icingaweb2 Monitoring Module for those users who are not yet ready to switch completely to IcingaDB Web? It could smooth the migration process.

Thanks and best regards
Jens

**Comment by martialblog** [comment]
Currently we haven't planned any major features to the Module, just doing maintenance and fixing longstanding bugs.

It might be possible to have a dedicated "v1 backports" branch, with patches for the v1 of the module. But currently that's not planned.

I'll discuss this with my colleagues.

**Comment by jensrudolf** [comment]
Thank you very much. I really appreciate your effort. I'll close this for now.
