### ISSUE TITLE
Rework enablelink option

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/icingaweb2-module-grafana#24]
There are open issues mentioning the missing link to Grafana in the 'iframe' mode. See https://github.com/Mikesch-mp/icingaweb2-module-grafana/pull/300

I think we could rework the 'link to Grafana' thing a bit.

Proposal:

- Always add a link to the Grafana Dashboard in the headline
- Remove the 'enable link' option entirely 

Preview:

![screenshot_2024-12-03-124440](https://github.com/user-attachments/assets/b3f82f6a-53d0-4a36-867e-eb6d7b330780)

Benefits:

- Makes the link more discoverable
- Same behavior for proxy and iframe mode
- Reduces conditionals from the code, thus less complexity

**Comment by martialblog** [comment]
@RincewindsHat @tbauriedel Any thoughts/ideas are welcome

**Comment by RincewindsHat** [comment]
I do like the idea. Is there any reason to disable that link ever?
Although, it might be possible, that people don't have access to Grafana at all and then then link is wasted space ... hm.

**Comment by martialblog** [comment]
Just saw, there's also a permission `$this->providePermission('grafana/enablelink', $this->translate('Allow to follow links to Grafana'));`

We could keep that just in case people want to disable the link for users

**Comment by SebastianOpeni** [comment]
Thank you very much for taking on the task of cleaning up and improving this icingaweb plugin :)
Since I found out about this fork I tried to keep up to date with your progress but I must have missed this one.

Just to add my thoughts to this topic:
Icingaweb2 allows to restrict users to only see certain hosts and services.
Such filtering is often done in a way not possible in Grafana => So it makes totally sense to not allow icingaweb-users to directly access Grafana, where they could request performance data not intended for their eyes.

All setups I remember utilizing this icingaweb module where build in this way.
To add a permanent link that for a larger group of setups could lead to nowhere would be an avoidable annoyance in my opinion.

**Comment by martialblog** [comment]
Hi, thanks for the feedback.

The fundamental issue that you point out here is, that the authorization model of Icinga Web and of Grafana are separate and there's is really no way to bridge them.

Like you said, one can restrict access to host/services in Icinga Web, but Grafana won't care about it.

That goes for both the Proxy and iFrame mode, since users can either just see the connection we make to the image renderer and adjust the requested data: `grafana/icingadbimg?host=server01&service=http&panelid=1&timerange=now-3h&timerangeto=now&cachetime=60
` or open the Grafana in the iFrame directly and request the data. Meaning, they can request data not intended for their eyes anyways with or without the link to Grafana. 

I figured, since we can't do anything about that anyways, we can at least simplify the codebase here and remove the `enablelink` stuff, thus improving the maintainability of the module in the longterm. 

But we'll keep you feedback in mind when this topic is ever brought up again.

**Comment by SebastianOpeni** [comment]
Hi @martialblog ,
thanks for your fast reply.

I did some testing and:
When I configure the Plugin to use the indirect Proxy Mode, I am not able to request a rendered grafana image for services I have no access to.

In the screenshot you can see two icingaweb users opening the same url.
One can access the (error) image, the other one gets a "service not found" message from icingaweb.
Both tried to open: 

http://localhost:4242/grafana/icingadbimg?host=icinga-master&service=ping4&panelid=1&timerange=now-6h&timerangeto=now&cachetime=0

![image](https://github.com/user-attachments/assets/8e63a6ac-05ea-491e-a9a8-35740f843472)

The filters for the second user's group are:

![image](https://github.com/user-attachments/assets/3d1f76bf-bb45-4d40-9f77-d09b72c89e86)

**Comment by SebastianOpeni** [comment]
For Services with the seen custom var, image creation was also possible for the non-admin user.

**Comment by SebastianOpeni** [comment]
Hi @martialblog ,

i hope I understood your remarks correctly and did not miss something.
I think the quick trial I did, proofed that for the proxy-mode the restrictions for users are correctly handled (he is blocked) by icingaweb.

If that is true, the szenario where direct grafana access is not possible for the icingaweb-users, is viable and brings the advantage that you only have to handle permissions and restrictions in one place.
For that usecase a reintroduction of the "hide the link" feature would be very advantageous.

Would it make sense to open a new issue for that? Or did i indeed miss some aspect here :see_no_evil: 

Best regards,

**Comment by martialblog** [comment]
Hi, you can open a new issue. Should be no problem to re-add the feature.
