### ISSUE TITLE
Proposal: Replace debug configuration option with URL parameter

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/icingaweb2-module-grafana#30]
Since the `debug` configuration option is only used in one location, we could replace it with an URL parameter:

users that have the permission can then simply add: `&debug` to the URL, not need to have access to the config of the module. `icingadb/service?name=ping4&host.name=homestead&host=homestead&service=ping4&timerange=7d&debug`

The change is fairly simple:

```
-        if ($this->debug && $this->permission->hasPermission('grafana/debug') && $report === false) {

+        if (Url::fromRequest()->hasParam('debug') && $this->permission->hasPermission('grafana/debug') && $report === false) {
```

Benefits:

- Users can have access to the debug information without having access to the module's config to enable it
- No need to fiddle in the config to enable/disable debug info

**Comment by martialblog** [comment]
@RincewindsHat @tbauriedel What do you think?

**Comment by martialblog** [comment]
Example: https://github.com/NETWAYS/icingaweb2-module-grafana/tree/feature/replace-debug

**Comment by RincewindsHat** [comment]
hm, okayish. But, put it prominently in the docu.
Or a button on every graph "debug info" or something like that.

**Comment by tbauriedel** [comment]
Sounds useful.  
A similar behaviour is already built into Icinga Director to dump SQL queries. But Lorenz is right. This must be well documented.  
The icingadb-web module do not have a `?debug` parameter as far as I know. But if this will be added in future, it could lead to problems.

**Comment by martialblog** [comment]
We could just name it `grafanaDebug` just to be safe.
